In [7]:

import pandas as pd
from sqlalchemy import create_engine,text
from urllib.parse import quote_plus

password = quote_plus("Aryan2003@")

engine = create_engine(
    f"mysql+pymysql://root:{password}@127.0.0.1:3306/company"
)

with engine.connect() as conn:
     conn.execute(
        text("CREATE DATABASE IF NOT EXISTS company")
    )
    # conn.commit()
print("Database Created Successfully!")

Database Created Successfully!

In [8]:
# checking tables present in the database 
engine = create_engine(
    f"mysql+pymysql://root:{password}@127.0.0.1:3306/company"
)
with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))

    for row in result:
        print(row)
        tables = pd.read_sql("SHOW TABLES", conn)
print(tables)

('begin_inventory',)
('end_inventory',)
('purchase_prices',)
('purchases',)
('sales',)
('vendor_invoice',)
('vendor_sales_summary',)
      Tables_in_company
0       begin_inventory
1         end_inventory
2       purchase_prices
3             purchases
4                 sales
5        vendor_invoice
6  vendor_sales_summary

In [9]:
with engine.connect() as conn:

    tables = pd.read_sql("SHOW TABLES", conn)

    for table in tables.iloc[:, 0]:

        print('-'*50, table, '-'*50)

        count = pd.read_sql(
            f"SELECT COUNT(*) as count FROM {table}",
            conn
        )

        print("Count of records:", count['count'].values[0])
        display(
            pd.read_sql(
                f"SELECT * FROM {table} LIMIT 5",
                conn
            )
        )

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [46]:
purchases = pd.read_sql_query(
        "SELECT * FROM purchases WHERE VendorNumber = 4466",
        engine
    )

purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750,2,24.32,10754,PERFECTA WINES

In [10]:

purchase_prices = pd.read_sql_query(
    "SELECT * FROM purchase_prices",
    engine
)

vendor_invoice = pd.read_sql_query(
    "SELECT * FROM vendor_invoice",
    engine
)
sales =pd.read_sql_query(
      "SELECT * FROM  sales",
    engine
)


purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750,2,24.32,10754,PERFECTA WINES

In [11]:
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,NaN
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,NaN
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,NaN
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,NaN
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,NaN
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,NaN

In [12]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
58         43341.54    28145.64           3446
60         18716.25    10720.79           1775
61          4364.88      363.74            312
62        119863.75    90154.51           3125
63        112249.22    88553.10           2778
...             ...         ...            ...
90089      19078.41     5759.52            159
90090       9749.85     4549.93             15
90604       9119.24     2639.78             76
90609       2074.17     1774.29             83
90631      31504.41    19502.73           1659

[11237 rows x 3 columns]

In [13]:
freight_summary = pd.read_sql_query("""
SELECT VendorNumber,
       SUM(Freight) AS FreightCost
FROM vendor_invoice
GROUP BY VendorNumber
""", engine)

In [14]:
purchase_summary = pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
    Where p.PurchasePrice > 0
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY TotalPurchaseDollars DESC
""", engine)

purchase_summary.head(10)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080.0,3811251.60
1,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038.0,3804041.22
2,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407.0,3418303.68
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682.0,3261197.94
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109.0,3023206.01
5,480,BACARDI USA INC,3858,17.77,750,23.99,138809.0,2466635.93
6,17035,PERNOD RICARD USA,2589,30.76,1750,39.99,70783.0,2177285.08
7,3960,DIAGEO NORTH AMERICA INC,3102,12.94,1750,17.99,161386.0,2088334.84
8,3960,DIAGEO NORTH AMERICA INC,3489,20.73,1750,27.99,91835.0,1903739.55
9,12546,JIM BEAM BRANDS COMPANY,1376,16.29,1750,21.99,108866.0,1773427.14

In [15]:
sales_summary = pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars DESC
""", engine)

sales_summary.head()

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,1128,1233,5.101920e+06,672819.31,142049.0,260999.20
1,4425,3405,4.819073e+06,561512.37,160247.0,294438.66
2,17035,8068,4.538121e+06,461140.15,187140.0,343854.07
3,3960,4261,4.475973e+06,420050.01,200412.0,368242.80
4,3960,3545,4.223108e+06,545778.28,135838.0,249587.83

In [16]:
import time

start = time.time()

final_table = pd.read_sql_query("""
SELECT
    pp.VendorNumber,
    pp.Brand,
    pp.Price AS ActualPrice,
    pp.PurchasePrice,

    SUM(s.SalesQuantity) AS TotalSalesQuantity,
    SUM(s.SalesDollars) AS TotalSalesDollars,
    SUM(s.SalesPrice) AS TotalSalesPrice,
    SUM(s.ExciseTax) AS TotalExciseTax,

    SUM(vi.Quantity) AS TotalPurchaseQuantity,
    SUM(vi.Dollars) AS TotalPurchaseDollars,
    SUM(vi.Freight) AS TotalFreightCost

FROM purchase_prices pp

JOIN sales s
    ON pp.VendorNumber = s.VendorNo
    AND pp.Brand = s.Brand

JOIN vendor_invoice vi
    ON pp.VendorNumber = vi.VendorNumber

GROUP BY
    pp.VendorNumber,
    pp.Brand,
    pp.Price,
    pp.PurchasePrice
""", engine)

end = time.time()

print("Time Taken:", round((end - start) / 60, 2), "minutes")

final_table.head()

Time Taken: 11.08 minutes

,VendorNumber,Brand,ActualPrice,PurchasePrice,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost
0,8112,115,27.99,21.37,564025.0,1.578706e+07,7.489424e+06,5.922262e+05,2.081573e+09,4.608612e+10,2.352094e+08
1,480,126,32.99,20.14,3190715.0,9.551360e+07,1.617272e+07,3.350251e+06,1.348729e+10,1.665680e+11,8.438445e+08
2,1128,171,49.99,36.76,362450.0,1.861388e+07,1.302615e+07,6.662513e+05,4.624137e+09,6.218127e+10,3.152933e+08
3,7245,175,36.99,26.80,39710.0,1.667423e+06,1.351028e+06,3.131755e+04,3.989946e+08,4.438997e+09,2.281195e+07
4,4425,211,24.99,19.83,204344.0,5.755095e+06,4.477826e+06,1.611284e+05,5.114476e+09,5.396809e+10,2.807279e+08

In [17]:

vendor_sales_summary = pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
""", engine)

In [18]:
vendor_sales_summary.dtypes

VendorNo                int64
Brand                   int64
TotalSalesDollars     float64
TotalSalesPrice       float64
TotalSalesQuantity    float64
TotalExciseTax        float64
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   VendorNo            0 non-null      object
 1   Brand               0 non-null      object
 2   TotalSalesDollars   0 non-null      int64
 3   TotalSalesPrice     0 non-null      int64
 4   TotalSalesQuantity  0 non-null      int64
 5   TotalExciseTax      0 non-null      int64
dtypes: int64(4), object(2)
memory usage: 132.0+ bytes

In [19]:
vendor_sales_summary["TotalSalesDollars"] = pd.to_numeric(
    vendor_sales_summary["TotalSalesDollars"]
)

vendor_sales_summary["TotalSalesPrice"] = pd.to_numeric(
    vendor_sales_summary["TotalSalesPrice"]
)

vendor_sales_summary["TotalSalesQuantity"] = pd.to_numeric(
    vendor_sales_summary["TotalSalesQuantity"]
)

vendor_sales_summary["TotalExciseTax"] = pd.to_numeric(
    vendor_sales_summary["TotalExciseTax"]
)

In [77]:
vendor_sales_summary.dtypes

VendorNo              object
Brand                 object
TotalSalesDollars      int64
TotalSalesPrice        int64
TotalSalesQuantity     int64
TotalExciseTax         int64
dtype: object

In [21]:
vendor_sales_summary.isnull().sum()

VendorNo              0
Brand                 0
TotalSalesDollars     0
TotalSalesPrice       0
TotalSalesQuantity    0
TotalExciseTax        0
dtype: int64

In [22]:
vendor_sales_summary = pd.read_sql_query("""
WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price,
        pp.Volume
),

SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost

FROM PurchaseSummary ps

LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand

LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber

ORDER BY ps.TotalPurchaseDollars DESC
""", engine)

vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07

Index(['VendorNo', 'Brand', 'TotalSalesDollars', 'TotalSalesPrice',
       'TotalSalesQuantity', 'TotalExciseTax'],
      dtype='str')

In [23]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [86]:
vendor_sales_summary['Description'].unique()

<StringArray>
[    'Jack Daniels No 7 Black',       'Tito's Handmade Vodka',
            'Absolut 80 Proof',      'Capt Morgan Spiced Rum',
             'Ketel One Vodka',            'Grey Goose Vodka',
       'Jameson Irish Whiskey',           'Smirnoff Traveler',
                   'Tanqueray',                    'Jim Beam',
 ...
         'Firefly Ridge Chard',           'Debauchery Pnt Nr',
 'Terruzzi & Puthod Vernaccia',  'Santa Rita Organic Svgn Bl',
    'Aresti Pnt Nr Curico Vly',   'Smirnoff Light Strawberry',
           'Crown Royal Apple', 'Concannon Glen Ellen Wh Zin',
 'The Club Strawbry Margarita', 'The Macallan Double Cask 12']
Length: 9652, dtype: str

In [88]:
vendor_sales_summary.isnull().sum()

VendorNumber                 0
VendorName                   0
Brand                        0
Description                  0
PurchasePrice                0
ActualPrice                  0
Volume                       0
TotalPurchaseQuantity        0
TotalPurchaseDollars         0
TotalSalesQuantity       10693
TotalSalesDollars        10693
TotalSalesPrice          10693
TotalExciseTax           10693
FreightCost                  0
dtype: int64

In [89]:
vendor_sales_summary['VendorName'].unique()

<StringArray>
['BROWN-FORMAN CORP          ',       'MARTIGNETTI COMPANIES',
 'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
 'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
 'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
 'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
 ...
             'UNCORKED       ', 'BRONCO WINE COMPANY        ',
 'MILTONS DISTRIBUTING CO    ', 'TRUETT HURST               ',
 'LAUREATE IMPORTS CO        ', 'FANTASY FINE WINES CORP    ',
 'AAPER ALCOHOL & CHEMICAL CO', 'SILVER MOUNTAIN CIDERS     ',
 'CAPSTONE INTERNATIONAL     ', 'FLAVOR ESSENCE INC         ']
Length: 129, dtype: str

In [91]:
vendor_sales_summary['Volume']=vendor_sales_summary['Volume'].astype('float64')

In [92]:
vendor_sales_summary.fillna(0, inplace=True)

vendor_sales_summary['VendorName'] = (
    vendor_sales_summary['VendorName'].str.strip()
)

In [24]:
vendor_sales_summary['GrossProfit'] = (
    vendor_sales_summary['TotalSalesDollars']
    - vendor_sales_summary['TotalPurchaseDollars']
)

In [95]:
vendor_sales_summary['GrossProfit'].min()

-3811251.600000111

In [25]:
import numpy as np

vendor_sales_summary['ProfitMargin'] = (
    vendor_sales_summary['GrossProfit']
    / vendor_sales_summary['TotalSalesDollars'].replace(0, np.nan)
) * 100

In [26]:
vendor_sales_summary['StockTurnover'] = (
    vendor_sales_summary['TotalSalesQuantity']
    / vendor_sales_summary['TotalPurchaseQuantity']
)

In [27]:
vendor_sales_summary['SalesToPurchaseRatio'] = (
    vendor_sales_summary['TotalSalesDollars']
    / vendor_sales_summary['TotalPurchaseDollars'].replace(0, np.nan)
)

In [29]:
with engine.connect() as conn:
    conn.execute(text("""
    CREATE TABLE vendor_sales_summary (

        VendorNumber INT,
        VendorName VARCHAR(100),
        Brand INT,
        Description VARCHAR(100),

        PurchasePrice DECIMAL(10,2),
        ActualPrice DECIMAL(10,2),

        Volume INT,

        TotalPurchaseQuantity INT,
        TotalPurchaseDollars DECIMAL(15,2),

        TotalSalesQuantity INT,
        TotalSalesDollars DECIMAL(15,2),
        TotalSalesPrice DECIMAL(15,2),

        TotalExciseTax DECIMAL(15,2),
        FreightCost DECIMAL(15,2),

        GrossProfit DECIMAL(15,2),
        ProfitMargin DECIMAL(15,2),
        StockTurnover DECIMAL(15,2),
        SalesToPurchaseRatio DECIMAL(15,2),

        PRIMARY KEY (VendorNumber, Brand)

    )
    """))

    conn.commit()

print("Table Created Successfully!")

OperationalError: (pymysql.err.OperationalError) (1050, "Table 'vendor_sales_summary' already exists")
[SQL:
    CREATE TABLE vendor_sales_summary (

        VendorNumber INT,
        VendorName VARCHAR(100),
        Brand INT,
        Description VARCHAR(100),

        PurchasePrice DECIMAL(10,2),
        ActualPrice DECIMAL(10,2),

        Volume INT,

        TotalPurchaseQuantity INT,
        TotalPurchaseDollars DECIMAL(15,2),

        TotalSalesQuantity INT,
        TotalSalesDollars DECIMAL(15,2),
        TotalSalesPrice DECIMAL(15,2),

        TotalExciseTax DECIMAL(15,2),
        FreightCost DECIMAL(15,2),

        GrossProfit DECIMAL(15,2),
        ProfitMargin DECIMAL(15,2),
        StockTurnover DECIMAL(15,2),
        SalesToPurchaseRatio DECIMAL(15,2),

        PRIMARY KEY (VendorNumber, Brand)

    )
    ]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [30]:
pd.read_sql_query(
    "SELECT * FROM vendor_sales_summary LIMIT 5",
    engine
)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [109]:
vendor_sales_summary.to_sql(
    'vendor_sales_summary',
    engine,
    if_exists='replace',
    index=False
)

10693

In [34]:
import pandas as pd
import numpy as np
import logging
import os
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Create logs folder
os.makedirs("logs", exist_ok=True)

# Logging configuration
logging.basicConfig(
    filename="logs/get_vendor_summary.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filemode="a"
)

logging.info("Program Started")


# =========================
# DATABASE CONNECTION
# =========================

password = quote_plus("Aryan2003@")

engine = create_engine(
    f"mysql+pymysql://root:{password}@127.0.0.1:3306/company"
)

# =========================
# CREATE VENDOR SUMMARY
# =========================

def create_vendor_summary(engine):

    query = """
    WITH FreightSummary AS (

        SELECT
            VendorNumber,
            SUM(Freight) AS FreightCost
        FROM vendor_invoice
        GROUP BY VendorNumber
    ),

    PurchaseSummary AS (

        SELECT
            p.VendorNumber,
            p.VendorName,
            p.Brand,
            p.Description,
            p.PurchasePrice,
            pp.Price AS ActualPrice,
            pp.Volume,

            SUM(p.Quantity) AS TotalPurchaseQuantity,
            SUM(p.Dollars) AS TotalPurchaseDollars

        FROM purchases p

        JOIN purchase_prices pp
            ON p.Brand = pp.Brand

        WHERE p.PurchasePrice > 0

        GROUP BY
            p.VendorNumber,
            p.VendorName,
            p.Brand,
            p.Description,
            p.PurchasePrice,
            pp.Price,
            pp.Volume
    ),

    SalesSummary AS (

        SELECT
            VendorNo,
            Brand,

            SUM(SalesQuantity) AS TotalSalesQuantity,
            SUM(SalesDollars) AS TotalSalesDollars,
            SUM(SalesPrice) AS TotalSalesPrice,
            SUM(ExciseTax) AS TotalExciseTax

        FROM sales

        GROUP BY VendorNo, Brand
    )

    SELECT

        ps.VendorNumber,
        ps.VendorName,
        ps.Brand,
        ps.Description,
        ps.PurchasePrice,
        ps.ActualPrice,
        ps.Volume,

        ps.TotalPurchaseQuantity,
        ps.TotalPurchaseDollars,

        ss.TotalSalesQuantity,
        ss.TotalSalesDollars,
        ss.TotalSalesPrice,
        ss.TotalExciseTax,

        fs.FreightCost

    FROM PurchaseSummary ps

    LEFT JOIN SalesSummary ss
        ON ps.VendorNumber = ss.VendorNo
        AND ps.Brand = ss.Brand

    LEFT JOIN FreightSummary fs
        ON ps.VendorNumber = fs.VendorNumber

    ORDER BY ps.TotalPurchaseDollars DESC
    """

    return pd.read_sql_query(query, engine)


# =========================
# CLEAN DATA
# =========================

def clean_data(df):

    df["Volume"] = pd.to_numeric(df["Volume"], errors="coerce")

    df.fillna(0, inplace=True)

    df["VendorName"] = df["VendorName"].astype(str).str.strip()
    df["Description"] = df["Description"].astype(str).str.strip()

    return df


# =========================
# FEATURE ENGINEERING
# =========================

import numpy as np
import pandas as pd

def add_metrics(df):

    # convert columns to numeric
    numeric_cols = [
        'TotalSalesDollars',
        'TotalPurchaseDollars',
        'TotalSalesQuantity',
        'TotalPurchaseQuantity'
    ]

    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # fill missing values
    df.fillna(0, inplace=True)

    # Gross Profit
    df['GrossProfit'] = (
        df['TotalSalesDollars']
        - df['TotalPurchaseDollars']
    )

    # Profit Margin
    df['ProfitMargin'] = (
        df['GrossProfit']
        /
        df['TotalSalesDollars'].replace(0, np.nan)
    ) * 100

    # Stock Turnover
    df['StockTurnover'] = (
        df['TotalSalesQuantity']
        /
        df['TotalPurchaseQuantity'].replace(0, np.nan)
    )

    # Sales To Purchase Ratio
    df['SalesToPurchaseRatio'] = (
        df['TotalSalesDollars']
        /
        df['TotalPurchaseDollars'].replace(0, np.nan)
    )

    # replace NaN created by division by zero
    df.fillna(0, inplace=True)

    return df

# =========================
# MAIN EXECUTION
# =========================

vendor_sales_summary = create_vendor_summary(engine)

vendor_sales_summary = clean_data(
    vendor_sales_summary
)

vendor_sales_summary = add_metrics(
    vendor_sales_summary
)

logging.info("Saving vendor_sales_summary table to MySQL")

vendor_sales_summary.to_sql(
    "vendor_sales_summary",
    con=engine,
    if_exists="replace",
    index=False
)

logging.info("vendor_sales_summary table created successfully")
summary_df = create_vendor_summary(engine)

logging.info(summary_df.head())
logging.info("Process Completed Successfully")
logging.shutdown()

In [5]:
import os

print(os.getcwd())
logging.info("Hello Aryan")
logging.info("Testing log file")
logging.shutdown()

C:\Users\Aryan Gupta\my project

In [36]:
create_vendor_summary(engine)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2.0,2.64,5.0,1.595000e+01,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6.0,2.34,134.0,6.566000e+01,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2.0,1.48,2.0,1.980000e+00,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1.0,1.47,72.0,1.432800e+02,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1.0,0.71,86.0,8.514000e+01,33.66,4.46,38994.78

In [37]:
vendor_sales_summary = create_vendor_summary(engine)

vendor_sales_summary = clean_data(vendor_sales_summary)

vendor_sales_summary = add_metrics(vendor_sales_summary)

vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [38]:
vendor_sales_summary[
    ['GrossProfit',
     'ProfitMargin',
     'StockTurnover',
     'SalesToPurchaseRatio']
].head()

   GrossProfit  ProfitMargin  StockTurnover  SalesToPurchaseRatio
0   1290667.91     25.297693       0.979108              1.338647
1   1015032.27     21.062810       0.976890              1.266830
2   1119816.92     24.675786       0.998575              1.327594
3   1214774.94     27.139908       0.993703              1.372493
4   1199901.61     28.412764       0.983556              1.396897

In [40]:
df=pd.read_sql_query(
    "SELECT COUNT(*) AS total_rows FROM vendor_sales_summary",
    engine
)
df.shape
df.head()

   total_rows
0       10692

In [41]:
df = pd.read_sql_query(
    "SELECT * FROM vendor_sales_summary",
    engine
)

print(df.shape)
df.head()

(10692, 18)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [42]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [44]:
vendor_sales_summary.to_csv(
    "vendor_sales_summary.csv",
    index=False
)

In [50]:
brand_performance.to_csv("BrandPerformance.csv", index=False)

top_vendors.to_csv("PurchaseContribution.csv", index=False)

low_turnover_vendors.to_csv("LowTurnoverVendor.csv", index=False)

NameError: name 'top_vendors' is not defined

In [47]:
dir()

['In',
 'Out',
 '_',
 '_10',
 '_11',
 '_12',
 '_14',
 '_15',
 '_16',
 '_18',
 '_20',
 '_21',
 '_22',
 '_23',
 '_30',
 '_36',
 '_37',
 '_38',
 '_39',
 '_40',
 '_41',
 '_42',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'add_metrics',
 'clean_data',
 'conn',
 'count',
 'create_engine',
 'create_vendor_summary',
 'df',
 'end',
 'engine',
 'exit',
 'file',
 'final_table',
 'freight_summary',
 'get_ipython',
 'logging',
 'np',
 'open',
 'os',
 'password',
 'pd',
 'purchase_prices',
 'purchase_summary',
 'quit',
 'quote_plus',
 'result',
 'row',
 'sales',
 'sales_summary',
 'start',
 'summary_df',
 'table',
 'tables',
 'text',
 'time',
 'vendor_invoice',
 'vendor_sales_summary']

In [48]:
brand_performance = df.groupby('Description').agg({
    'TotalSalesDollars': 'sum',
    'ProfitMargin': 'mean'
}).reset_index()

In [49]:
brand_performance.head()

                    Description  TotalSalesDollars  ProfitMargin
0                        (RI) 1           21519.09     18.060661
1       .nparalleled Svgn Blanc            1094.63     29.978166
2           10 Span Cab Svgn CC            2703.89     20.937612
3              10 Span Chard CC            3325.56     27.806445
4  10 Span Pnt Gris Monterey Cy            2082.22     32.226182

In [51]:
vendor_performance = df.groupby('VendorName').agg({
    'TotalPurchaseDollars': 'sum',
    'GrossProfit': 'sum',
    'TotalSalesDollars': 'sum'
}).reset_index()

vendor_performance['PurchaseContribution%'] = (
    vendor_performance['TotalPurchaseDollars']
    / vendor_performance['TotalPurchaseDollars'].sum()
) * 100

vendor_performance = vendor_performance.sort_values(
    'PurchaseContribution%',
    ascending=False
)

top_vendors = vendor_performance.head(10)

In [52]:
top_vendors.to_csv(
    "PurchaseContribution.csv",
    index=False
)

In [53]:
low_turnover_vendors = (
    df[df['StockTurnover'] < 1]
    .groupby('VendorName')[['StockTurnover']]
    .mean()
    .sort_values('StockTurnover')
    .head(10)
)

low_turnover_vendors.to_csv(
    "LowTurnoverVendor.csv",
    index=False
)

In [54]:
dir()

['In',
 'Out',
 '_',
 '_10',
 '_11',
 '_12',
 '_14',
 '_15',
 '_16',
 '_18',
 '_20',
 '_21',
 '_22',
 '_23',
 '_30',
 '_36',
 '_37',
 '_38',
 '_39',
 '_40',
 '_41',
 '_42',
 '_47',
 '_49',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'add_metrics',
 'brand_performance',
 'clean_data',
 'conn',
 'count',
 'create_engine',
 'create_vendor_summary',
 'df',
 'end',
 'engine',
 'exit',
 'file',
 'final_table',
 'freight_summary',
 'get_ipython',
 'logging',
 'low_turnover_vendors',
 'np',
 'open',
 'os',
 'password',
 'pd',
 'purchase_prices',
 'purchase_summary',
 'quit',
 'quote_plus',
 'result',
 'row',
 'sales',
 'sales_summary',
 'start',
 'summary_df',
 'table',
 'tables',
 'text',
 'time',
 'top_vendors',
 'vendor_invoice',
 'vendor_performance',
 'vendor_sales_summary']

In [55]:
for file in os.listdir():
    if file.endswith(".csv"):
        print(file)

begin_inventory.csv
BrandPerformance.csv
end_inventory.csv
LowTurnoverVendor.csv
PurchaseContribution.csv
purchases.csv
purchase_prices.csv
sales.csv
vendor_invoice.csv
vendor_sales_summary.csv

In [56]:
print(os.getcwd())

C:\Users\Aryan Gupta\my project

In [57]:
for file in os.listdir():
    if file.endswith(".csv"):
        print(file)

begin_inventory.csv
BrandPerformance.csv
end_inventory.csv
LowTurnoverVendor.csv
PurchaseContribution.csv
purchases.csv
purchase_prices.csv
sales.csv
vendor_invoice.csv
vendor_sales_summary.csv